from setuptools import setup, find_packages
import os

version = '1.12.dev0'

setup(name='ilo.policy',
      version=version,
      description="",
      long_description=open("README.rst").read() + "\n" +
                       open(os.path.join("docs", "HISTORY.rst")).read(),
      # Get more strings from
      # http://pypi.python.org/pypi?%3Aaction=list_classifiers
      classifiers=[
        "Framework :: Plone",
        "Programming Language :: Python",
        "Topic :: Software Development :: Libraries :: Python Modules",
        ],
      keywords='',
      author='Inigo Consulting',
      author_email='team@inigo-tech.com',
      url='http://github.com/inigoconsulting/',
      license='gpl',
      packages=find_packages(),
      namespace_packages=['ilo'],
      include_package_data=True,
      zip_safe=False,
      install_requires=[
          'setuptools',
          'plone.app.dexterity',
          'plone.namedfile [blobs]',
          'collective.grok',
          'plone.app.async',
          'plone.app.theming',
          'ilo.compatplone3',
          'Products.contentmigration',
          'Products.PloneHelpCenter',
          'Products.PloneBooking',
          'Products.Ploneboard',
          'Products.CompoundField',
          'plone.app.caching',
          'Products.ATExtensions',
          'Products.ContentWellPortlets',
          'Products.ManagableIndex',
          'collective.atautocomplete',
          'collective.ATClamAV',
          'collective.externaleditor',
          'collective.quickupload',
          'collective.formcriteria',
          'collective.flexitopic',
          'collective.contentleadimage',
          'collective.contacts',
          'collective.portlet.usertrack',
          'collective.portlet.collectionmultiview',
          'collective.portlet.collectionmultiview_extrarenderers',
          'collective.stats',
          'collective.sendaspdf',
          'collective.documentviewer',
          'Solgema.fullcalendar',
          'ilo.mailreport',
          'collective.mediaelementjs',
          'ilo.portlets',
          'ilo.theme',
          'ilo.customizations',
          'Products.PlonePopoll',
          'dateable.kalends',
          'Products.TinyMCE',
          'collective.contentrules.mailtolocalrole',
          'collective.kuputabs',
          'qi.LiveChat',
          'munin.zope',
          'redturtle.video',
          'pisa',
          'pyPdf',
          'html5lib',
          'reportlab',
          'atreal.richfile.preview',
          'Products.AdvancedQuery',
          'Products.OpenXml',
          'ilo.contentrules',
          'Products.PloneTemplates',
          'plone.app.dexterity',
          'Products.feedfeeder',
          'ilo.publications',
          'ilo.vocabularies',
          'collective.solr',
          'eea.facetednavigation',
          'Twisted',
          'plone.app.referenceablebehavior',
          'ilo.chatbox',
          'python-ldap',
          'collective.sortmyfolder',
          'xhtml2pdf',
          'Products.PloneKeywordManager',
          'collective.mediaelementjs',
          'Products.ILOIntranetTypes',
          'Products.DWCPReports',
          'Products.ILOProjectEvaluation',
          'collective.plonetruegallery[all]',
          'collective.xmpp.core',
          'collective.xmpp.chat',
          'ilo.missionreportstats',
          'plonesocial.suite',
          'Products.RedirectionTool',
          'webcouturier.dropdownmenu',
          'iloksp.caching',
          'ploneun.consultant',
          'ploneun.sharingnotification',
          'ploneun.tor',
          'iloactemp.backgroundnote',
          'ploneun.subscribetochanges',
          'eea.daviz',
          # -*- Extra requirements: -*-
      ],
      extras_require={
          'test': [
              'plone.app.testing',
           ],
      },
      entry_points="""
      # -*- Entry points: -*-
      [z3c.autoinclude.plugin]
      target = plone
      """,
      # The next two lines may be deleted after you no longer need
      # addcontent support from paster and before you distribute
      # your package.
      setup_requires=["PasteScript"],
      paster_plugins=["templer.localcommands"],

      )
